font:
  size: 14
  normal:
    family: Iosevka Nerd Font Mono
    style: Regular
  bold:
    family: Iosevka Nerd Font Mono
    style: Bold
  italic:
    family: Iosevka Nerd Font Mono
    style: Italic

