{
  pkgs,
  config,
  lib,
  ...
}:
let
  cfg = config.skr.home.pi;

  apiKey = "modal-endpoint";
  modelsConfig = {
    providers = {
      modal-labs = {
        baseUrl = "https://modal-labs-lukas-dev--ep-kimi-k3-server.us-west.modal.direct/v1";
        api = "openai-completions";
        apiKey = "!cat ${config.age.secrets.${apiKey}.path}";
        models = [
          {
            id = "moonshotai/Kimi-K3";
            name = "Kimi K3";
            input = [
              "text"
              "image"
            ];
            contextWindow = 1048576;
            reasoning = true;
            # Most of the thinking levels are turned off for the model, server will respond with
            # 400 to unsupported levels.
            thinkingLevelMap = {
              low = "low";
              high = "high";
              max = "max";
              off = null;
              minimal = null;
              medium = null;
              xhigh = null;
            };
          }
        ];
      };
    };
  };

  settings = {
    defaultProvider = "modal-labs";
    defaultModel = "moonshotai/Kimi-K3";
  };

in
{
  options.skr.home.pi = {
    enable = lib.mkOption {
      description = "Toggle to enable pi.";
      type = lib.types.bool;
      default = false;
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ pkgs.pi-coding-agent ];

    # Config is not placed in XDG folders unfortunately...
    home.file = {
      ".pi/agent/models.json".text = builtins.toJSON modelsConfig;
      ".pi/agent/settings.json" = {
        text = builtins.toJSON settings;
        # Force replace the file: this gets autogenerated by pi if not present.
        force = true;
      };
    };

    age.secrets.${apiKey} = {
      file = ../../secrets/modal-endpoint.age;
      path = "${config.home.homeDirectory}/.secrets/MODAL_ENDPOINT_API";
    };
  };
}
