{
  pkgs,
  config,
  lib,
  ...
}:
let
  cfg = config.skr.home.pi;

  apiKey = "evroc-think";
  modelsConfig = {
    providers = {
      evroc = {
        baseUrl = "https://models.think.evroc.com/v1";
        api = "openai-completions";
        apiKey = "!cat ${config.age.secrets.${apiKey}.path}";
        models = [
          {
            id = "moonshotai/Kimi-K2.5";
            name = "Kimi K2.5";
            input = [
              "text"
              "image"
            ];
            contextWindow = 200000;
            reasoning = true;
          }
          {
            id = "moonshotai/Kimi-K2.6";
            name = "Kimi K2.6";
            input = [
              "text"
              "image"
            ];
            contextWindow = 200000;
            reasoning = true;
          }
          {
            id = "zai-org/GLM-5.2";
            name = "GLM 5.2";
            input = [
              "text"
              "image"
            ];
            contextWindow = 200000;
            reasoning = true;
          }
        ];
      };
    };
  };

  settings = {
    defaultProvider = "evroc";
    defaultModel = "zai-org/GLM-5.2";
  };

in
{
  options.skr.home.pi = {
    enable = lib.mkOption {
      description = "Toggle to enable pi.";
      type = lib.types.bool;
      default = false;
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ pkgs.pi-coding-agent ];

    # Config is not placed in XDG folders unfortunately...
    home.file = {
      ".pi/agent/models.json".text = builtins.toJSON modelsConfig;
      ".pi/agent/settings.json" = {
        text = builtins.toJSON settings;
        # Force replace the file: this gets autogenerated by pi if not present.
        force = true;
      };
    };

    # TODO: repeat API key for the opencode module. Put it as a separate agenix
    # secret and on a different path now, but should be able to share this.
    # Figure out some good abstraction.
    age.secrets.${apiKey} = {
      file = ../../secrets/evroc-think-api-key.age;
      path = "${config.home.homeDirectory}/.secrets/EVROC_THINK_API";
    };
  };
}
