[user]
name = "Lukas Bjarre"
email = "lukas.bjarre@gmail.com"

[[--scope]]
--when.repositories = ["~/src/github.com/modal-labs", "~/src/github.com/modal-projects"]
[--scope.user]
email = "lukas@modal.com"
[--scope.signing]
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHAPZT7/jOrDlplzrZ+mvA2ToS50hcPVm897WehsEa9d lukas@modal.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[signing.backends.ssh]
program = "ssh-keygen"

[git]
sign-on-push = true
# Private commits: refuse to push commits that starts with 'PRIVATE:'.
private-commits = "subject(glob:'PRIVATE:*')"

[ui]
default-command = ["log", "--no-pager"]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[templates]
draft_commit_description = '''
join("\n",
  builtin_draft_commit_description,
  "JJ: The rest of this file is ignored after the next line",
  "JJ: ignore-rest",
  "",
  "JJ: diff.stat():",
  diff.stat(),
  "JJ: diff.git():",
  diff.git(),
)
'''

[aliases]
tug = {
    doc = "Move closest bookmark to the closest non-empty change.",
    definition = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_nonempty(@)"],
}
restack = {
    doc = "Rebase all work-in-progress local changes onto trunk.",
    definition = ["rebase", "--source", "roots(mutable())", "--destination", "trunk()"],
}
sync = {
    doc = "Fetch from remote and restack all work-in-progress.",
    # TODO: Maybe want to jj git push also? Keeping it off for now.
    definition = ["util", "exec", "bash", "--", "-c", "jj git fetch && jj restack"],
}
stack-bookmarks = {
    doc = "Local bookmarks in substack().",
    definition = [
        "log",
        "--revision", "substack()",
        "--template", "self.local_bookmarks().map(|b| b.name()).join(' ') ++ ' '",
        "--no-graph",
        "--reversed",
    ],
}

[revsets]
# Default log revset: pretty much the default, but show some more trunk ancestors.
log = 'present(@) | ancestors(immutable_heads().., 3) | ancestors(trunk(), 3)'

[revset-aliases]
"closest_bookmark()" = {
    doc = "The closest bookmark.",
    definition = "closest_bookmark(@)",
}
"closest_bookmark(to)" = {
    doc = "The closest bookmark in the ancestors of 'to'.",
    definition = "heads(::to & bookmarks())",
}
"closest_nonempty()" = {
    doc = "The closest non-empty revision.",
    definition = "closest_nonempty(@)",
}
"closest_nonempty(to)" = {
    doc = "The closest non-empty revision in the ancestors of 'to'.",
    definition = "heads(::to ~ empty())",
}
"stack()" = {
    doc = "All revisions of the current stack.",
    definition = "stack(@)",
}
"stack(to)" = {
    doc = "All revisions in the stack that revision 'to' belongs to.",
    definition = "stack_bottom(to)::stack_top(to)",
}
"substack()" = {
    doc = "stack(@) but upper capped at '@'.",
    definition = "substack(@)",
}
"substack(to)" = {
    doc = "stack(to) but upper capped at 'to'.",
    definition = "stack_bottom(to)::to",
}
"stack_bottom()" = {
    doc = "Bottom of the current stack.",
    definition = "stack_bottom(@)",
}
"stack_bottom(to)" = {
    doc = "Bottom of the stack that revision 'to' belongs to.",
    definition = "roots(mutable() & ::to)",
}
"stack_top()" = {
    doc = "Top of the current stack.",
    definition = "stack_top(@)",
}
"stack_top(to)" = {
    doc = "Top of the stack that revision 'to' belongs to. Must resolve to exactly one revision.",
    definition = "exactly(stack_heads(to), 1)",
}
"stack_heads()" = {
    doc = "Heads of the current stack.",
    definition = "stack_heads(@)",
}
"stack_heads(to)" = {
    doc = "Heads of the stack that revision 'to' belongs to.",
    definition = "heads(mutable() & to::)",
}

